services:
  postgres:
    image: postgres:17
    container_name: servicio-marketplace-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace_password
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
